export const visualModels = {
  a: {
    name: 'Táctico Sci-Fi Limpio',
    colors: {
      primary: '#00d9ff',
      secondary: '#ffb800',
      background: '#1a2332',
      backgroundLight: '#243447',
      surface: '#2a3f5c',
      text: '#ffffff',
      textSecondary: '#94a3b8',
      accent: '#00d9ff',
      success: '#00ff88',
      danger: '#ff4757',
      warning: '#ffb800',
    },
    fonts: {
      heading: 'Space Grotesk, system-ui, sans-serif',
      body: 'Manrope, system-ui, sans-serif',
    },
    radius: '4px',
    style: 'clean',
  },
  b: {
    name: 'Arcade Energético',
    colors: {
      primary: '#ff1744',
      secondary: '#ffea00',
      background: '#1a0033',
      backgroundLight: '#2d0052',
      surface: '#4a0080',
      text: '#ffffff',
      textSecondary: '#c792ea',
      accent: '#ff1744',
      success: '#00ff41',
      danger: '#ff1744',
      warning: '#ffea00',
    },
    fonts: {
      heading: 'system-ui, sans-serif',
      body: 'system-ui, sans-serif',
    },
    radius: '16px',
    style: 'vibrant',
  },
  c: {
    name: 'Neo Militar Minimal',
    colors: {
      primary: '#7cb342',
      secondary: '#ff9800',
      background: '#0d1117',
      backgroundLight: '#161b22',
      surface: '#21262d',
      text: '#c9d1d9',
      textSecondary: '#8b949e',
      accent: '#7cb342',
      success: '#7cb342',
      danger: '#ff5252',
      warning: '#ff9800',
    },
    fonts: {
      heading: 'system-ui, monospace',
      body: 'system-ui, monospace',
    },
    radius: '2px',
    style: 'tactical',
  },
  d: {
    name: 'Fantasy Tech Elegante',
    colors: {
      primary: '#9c27b0',
      secondary: '#ffab40',
      background: '#0a0e1a',
      backgroundLight: '#141829',
      surface: '#1e2537',
      text: '#e8def8',
      textSecondary: '#a894c7',
      accent: '#9c27b0',
      success: '#66bb6a',
      danger: '#ef5350',
      warning: '#ffab40',
    },
    fonts: {
      heading: 'Georgia, serif',
      body: 'system-ui, sans-serif',
    },
    radius: '8px',
    style: 'elegant',
  },
  e: {
    name: 'Esports Broadcast',
    colors: {
      primary: '#0a84ff',
      secondary: '#ff453a',
      background: '#000000',
      backgroundLight: '#1c1c1e',
      surface: '#2c2c2e',
      text: '#ffffff',
      textSecondary: '#98989d',
      accent: '#0a84ff',
      success: '#30d158',
      danger: '#ff453a',
      warning: '#ffd60a',
    },
    fonts: {
      heading: 'system-ui, sans-serif',
      body: 'system-ui, sans-serif',
    },
    radius: '6px',
    style: 'broadcast',
  },
};

export type ModelKey = keyof typeof visualModels;
