services:
  _defaults:
    autowire: true
    autoconfigure: true

  Doctrine\Migrations\DependencyFactory:
    alias: doctrine.migrations.dependency_factory

  App\:
    resource: '../src/'
    exclude:
      - '../src/Entity/'

  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']

  App\Service\TokenService:
    arguments:
      $secret: '%env(APP_SECRET)%'
